#Sets up a Kubernetes deployment that ensures our microservice remains operational
apiVersion: apps/v1
kind: Deployment 
#Sets the name of the deployment
metadata:
  name: book-catalog 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: book-catalog 
  #A template for the pod designed to run our microservice
  template: 
    metadata:
      labels:
        app: book-catalog 
    spec:
      containers: 
      - name: book-catalog
        image: sit722project3.azurecr.io/book-catalog:1 
        imagePullPolicy: IfNotPresent 
        env: 
        - name: PORT
          value: "4001" 
#Divides the configuration file into other sections
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management
        image: sit722project3.azurecr.io/inventory-management:1
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "4002"
--- #Divides the configuration file into two main sections
apiVersion: v1
kind: Service 
metadata:
  name: book-catalog 
spec:
  selector:
    app: book-catalog 
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4002